### ISSUE TITLE
How to change the duration of each episode of tasks?

### ISSUE THREAD

**Issue by wjyustl** [ScheiklP/sofa_zoo#8]
Hi, @ScheiklP 
![Snipaste_2024-01-31_17-37-26](https://github.com/ScheiklP/sofa_zoo/assets/129915667/6c812a58-599b-48f1-a46d-fafb2150f2cb)
I'm not sure if this line in the picture refers to task time.

I can see from the rendered visualizations that each round takes only 20 seconds to complete. Whether the task is completed or not, the next round of tasks will proceed 20 seconds later.
I think 20 seconds is a little too short, and I wish I could give the task more time to process so that it can properly complete the task that it is supposed to succeed.

https://github.com/ScheiklP/sofa_zoo/assets/129915667/b8ea8ab4-9acb-4623-80d8-af5a73d022dc
The video shows a new round of missions starting at the 20-second mark.

**Comment by ScheiklP** [comment]
Hi @wjyustl,
ep_len_mean is the mean episode length measured in environment steps.
With a dt of 0.1 seconds, 200 steps is 20 seconds, so that checks out.
If you want to increase the timeout (allow for more environment steps before it is reset), you can adjust the `max_episode_steps` parameter [here](https://github.com/ScheiklP/sofa_zoo/blob/main/sofa_zoo/envs/rope_threading/ppo.py#L88).

**Comment by wjyustl** [comment]
@ScheiklP 
Because I often find that the task is not finished at 20 seconds. I feel like with a little more time, maybe he could've done it. So I want to try to extend the time to improve the success rate of the mission.
If I get new results, I will get back to you. Thank you very much!
